import { types } from 'mobx-state-tree';

export const SingleUserModel = types.model('', {
  login: types.optional(types.string, ''),
  id: 2,
  node_id: types.optional(types.string, ''),
  avatar_url: types.optional(types.string, ''),
  gravatar_id: types.optional(types.string, ''),
  url: types.optional(types.string, ''),
  html_url: types.optional(types.string, ''),
  followers_url: types.optional(types.string, ''),
  following_url: types.optional(types.string, ''),
  gists_url: types.optional(types.string, ''),
  starred_url: types.optional(types.string, ''),
  subscriptions_url: types.optional(types.string, ''),
  organizations_url: types.optional(types.string, ''),
  repos_url: types.optional(types.string, ''),
  events_url: types.optional(types.string, ''),
  received_events_url: types.optional(types.string, ''),
  type: types.optional(types.string, ''),
  site_admin: types.optional(types.boolean, false),
  name: types.maybeNull(types.string),
  company: types.maybeNull(types.string),
  blog: types.optional(types.string, ''),
  location: types.maybeNull(types.string),
  email: types.maybeNull(types.string),
  hireable: types.maybeNull(types.boolean),
  bio: types.maybeNull(types.string),
  twitter_username: types.maybeNull(types.string),
  public_repos: types.optional(types.number, 0),
  public_gists: types.optional(types.number, 0),
  followers: types.optional(types.number, 0),
  following: types.optional(types.number, 0),
  created_at: types.optional(types.string, ''),
  updated_at: types.optional(types.string, '')
});

export const UserModel = types.model('UserModel', {
  login: types.optional(types.string, ''),
  id: types.maybeNull(types.number),
  node_id: types.maybeNull(types.string),
  avatar_url: types.optional(types.string, ''),
  gravatar_id: types.optional(types.string, ''),
  url: types.optional(types.string, ''),
  html_url: types.optional(types.string, ''),
  followers_url: types.optional(types.string, ''),
  following_url: types.optional(types.string, ''),
  gists_url: types.optional(types.string, ''),
  starred_url: types.optional(types.string, ''),
  subscriptions_url: types.optional(types.string, ''),
  organizations_url: types.optional(types.string, ''),
  repos_url: types.optional(types.string, ''),
  events_url: types.optional(types.string, ''),
  received_events_url: types.optional(types.string, ''),
  type: types.optional(types.string, ''),
  site_admin: types.optional(types.boolean, false)
});
